/*
 * Code generated from Atmel Start.
 *
 * This file will be overwritten when reconfiguring your Atmel Start project.
 * Please copy examples or other code you want to keep to a separate file
 * to avoid losing it when reconfiguring.
 */
#ifndef ATMEL_START_PINS_H_INCLUDED
#define ATMEL_START_PINS_H_INCLUDED

#include <hal_gpio.h>

// SAME54 has 14 pin functions

#define GPIO_PIN_FUNCTION_A 0
#define GPIO_PIN_FUNCTION_B 1
#define GPIO_PIN_FUNCTION_C 2
#define GPIO_PIN_FUNCTION_D 3
#define GPIO_PIN_FUNCTION_E 4
#define GPIO_PIN_FUNCTION_F 5
#define GPIO_PIN_FUNCTION_G 6
#define GPIO_PIN_FUNCTION_H 7
#define GPIO_PIN_FUNCTION_I 8
#define GPIO_PIN_FUNCTION_J 9
#define GPIO_PIN_FUNCTION_K 10
#define GPIO_PIN_FUNCTION_L 11
#define GPIO_PIN_FUNCTION_M 12
#define GPIO_PIN_FUNCTION_N 13

#define PROJECTILE_CHARGE_VOLTAGE_AO GPIO(GPIO_PORTA, 2)
#define PROJECTILE_CHARGE_CURRENT_AO GPIO(GPIO_PORTA, 5)
#define ERROR_LED_OP GPIO(GPIO_PORTA, 6)
#define STATUS_LED_OP GPIO(GPIO_PORTA, 7)
#define QSPI_IO0 GPIO(GPIO_PORTA, 8)
#define QSPI_IO1 GPIO(GPIO_PORTA, 9)
#define QSPI_IO2 GPIO(GPIO_PORTA, 10)
#define QSPI_IO3 GPIO(GPIO_PORTA, 11)
#define PROJECTILE_FITTED_FB GPIO(GPIO_PORTA, 20)
#define PROJECTILE_MISO GPIO(GPIO_PORTA, 21)
#define PROJECTILE_SCK GPIO(GPIO_PORTA, 22)
#define PROJECTILE_MOSI GPIO(GPIO_PORTA, 23)
#define USB_DN GPIO(GPIO_PORTA, 24)
#define USB_DP GPIO(GPIO_PORTA, 25)
#define BREECH_LOCK_MOTOR_DIR_OP GPIO(GPIO_PORTB, 0)
#define BREECH_CLOSE_MOTORCLK_OP GPIO(GPIO_PORTB, 1)
#define BREECH_LOCK_MOTOR_CLKOP GPIO(GPIO_PORTB, 2)
#define HW_VERSION_AN GPIO(GPIO_PORTB, 4)
#define RES_PRESSURE_A_AN GPIO(GPIO_PORTB, 5)
#define PROJECTILE_CHARGE_VOLTAGE_AN GPIO(GPIO_PORTB, 8)
#define PROJECTILE_CHARGE_CURRENT_AN GPIO(GPIO_PORTB, 9)
#define QSPI_SCK GPIO(GPIO_PORTB, 10)
#define QSPI_CS GPIO(GPIO_PORTB, 11)
#define DIAG_COMMS_RX GPIO(GPIO_PORTB, 12)
#define DIAG_COMMS_TX GPIO(GPIO_PORTB, 13)
#define FILL_VALVE_FINE_OP GPIO(GPIO_PORTB, 16)
#define FILL_VALVE_COARSE_OP GPIO(GPIO_PORTB, 17)
#define PROJECTILE_COMMS_ENABLE_OP GPIO(GPIO_PORTB, 21)
#define TRIGGER_SAFE_SWITCH_FB GPIO(GPIO_PORTB, 25)
#define BREECH_CLOSED_SWITCH_FB GPIO(GPIO_PORTB, 26)
#define BREECH_OPEN_SWITCH_FB GPIO(GPIO_PORTB, 27)
#define BREECH_UNLOCKED_SWITCH_FB GPIO(GPIO_PORTB, 28)
#define BREECH_LOCKED_SWITCH_FB GPIO(GPIO_PORTB, 29)
#define BREECH_MOTOR_nSLEEP_OP GPIO(GPIO_PORTB, 31)
#define PROJECTILE_CURRENT_FB GPIO(GPIO_PORTC, 5)
#define PROJECTILE_VOLTAGE_FB GPIO(GPIO_PORTC, 6)
#define SYSTEM_PRESSURE_ENABLE_FB GPIO(GPIO_PORTC, 22)
#define SYSTEM_CHARGE_ENABLE_FB GPIO(GPIO_PORTC, 23)
#define SERIAL_MODE_OP GPIO(GPIO_PORTC, 26)
#define SYSTEM_COMMS_RX GPIO(GPIO_PORTC, 27)
#define SYSTEM_COMMS_TX GPIO(GPIO_PORTC, 28)
#define BREECH_MOTOR_nENABLE_OP GPIO(GPIO_PORTC, 30)
#define BREECH_CLOSE_MOTOR_DIR_OP GPIO(GPIO_PORTC, 31)
#define RES_PRESSURE_B_AN GPIO(GPIO_PORTD, 0)
#define DUMP_VALVE_FINE_OP GPIO(GPIO_PORTD, 20)
#define DUMP_VALVE_COARSE_OP GPIO(GPIO_PORTD, 21)

#endif // ATMEL_START_PINS_H_INCLUDED
